# -*- coding: utf-8 -*-`nfrom __future__ import annotations
import json, sys
from pathlib import Path
from statistics import mean
import psycopg
from psycopg.rows import dict_row
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'services'/'crawler'/'src'))
from fratfinder_crawler.config import get_settings
RUN_ID='stress-20260409-full'
REPORT=ROOT/'docs'/'reports'/'stress'/'FUNCTIONALITY_REPORT_2026-04-09.md'
JSONL=ROOT/'docs'/'reports'/'stress'/'stress-20260409-full.jsonl'
PROBES=['"sigma chi" University of Virginia instagram','"delta chi" Mississippi State chapter website','"lambda chi alpha" Purdue contact email','"phi gamma delta" chapter directory']
def md(x):
    return '' if x is None else str(x).replace('|','\\|').replace('\n','<br>')
def provsum(items):
    items=items or []
    return 'attempts={}; success={}; unavailable={}; request_error={}; low_signal={}; circuit_open={}'.format(len(items),sum(1 for a in items if a.get('status')=='success'),sum(1 for a in items if a.get('status')=='unavailable'),sum(1 for a in items if a.get('status')=='request_error'),sum(1 for a in items if a.get('status')=='low_signal'),sum(1 for a in items if a.get('circuit_open')))
def qpath(trace,max_items=6):
    qs=[]
    for it in trace or []:
        if it.get('event') in ('search_executed','search_cache_hit') and it.get('query'):
            kind='cache' if it['event']=='search_cache_hit' else 'search'
            qs.append(f"{kind}: {it['query']} ({it.get('result_count')})")
    if not qs: return 'none'
    shown=qs[:max_items]
    txt='<br>'.join(md(q) for q in shown)
    return txt if len(qs)<=max_items else txt+f"<br>... (+{len(qs)-max_items} more)"
def tevents(trace,max_items=6):
    keep={'job_started','load_context','admission_gate','chapter_activity_validation','website_strategy','candidate_selected','official_domain_verified'}
    ev=[]
    for it in trace or []:
        e=it.get('event')
        if e in keep:
            s=e
            if 'status' in it: s+=f": {it['status']}"
            if 'stage' in it: s+=f": {it['stage']}"
            if 'target' in it: s+=f": {it['target']}"
            if 'decision' in it: s+=f": {it['decision']}"
            ev.append(s)
    if not ev: return 'none'
    shown=ev[:max_items]
    txt='<br>'.join(md(e) for e in shown)
    return txt if len(ev)<=max_items else txt+f"<br>... (+{len(ev)-max_items} more)"
def add_table(lines,title,intro,headers,rows):
    lines.append(f'## {title}\n')
    if intro: lines.append(intro+'\n')
    lines.append('| '+' | '.join(headers)+' |')
    lines.append('| '+' | '.join(['---']*len(headers))+' |')
    for r in rows: lines.append('| '+' | '.join(md(x) for x in r)+' |')
    lines.append('')
rows=[json.loads(line) for line in JSONL.read_text(encoding='utf-8').splitlines() if line.strip()]
batches=[r for r in rows if r['type']=='batch_progress']
first_ts,last_ts=rows[0]['timestamp'],rows[-1]['timestamp']
peak_jpm=max(b['batch_result']['jobs_per_minute'] for b in batches)
min_jpm=min(b['batch_result']['jobs_per_minute'] for b in batches)
avg_jpm=round(mean(b['batch_result']['jobs_per_minute'] for b in batches),2)
processed_total=sum(b['batch_result']['processed'] for b in batches)
requeued_total=sum(b['batch_result']['requeued'] for b in batches)
settings=get_settings()
with psycopg.connect(settings.database_url,row_factory=dict_row) as conn:
  with conn.cursor() as cur:
    cur.execute("""select count(*) filter (where payload->>'stressRunId'=%s)::int as job_count,count(distinct chapter_id) filter (where payload->>'stressRunId'=%s)::int as chapter_count,count(*) filter (where payload->>'stressRunId'=%s and status='done')::int as done_jobs,count(*) filter (where payload->>'stressRunId'=%s and status='failed')::int as failed_jobs,count(*) filter (where payload->>'stressRunId'=%s and status='queued' and queue_state='actionable')::int as queued_actionable,count(*) filter (where payload->>'stressRunId'=%s and status='queued' and queue_state='deferred')::int as queued_deferred,count(*) filter (where payload->>'stressRunId'=%s and status='running')::int as running_jobs from field_jobs""",(RUN_ID,)*7); summary=cur.fetchone()
    cur.execute("""select field_name,count(*) filter (where status='done')::int as done_count,count(*) filter (where status='failed')::int as failed_count,count(*) filter (where status='queued' and queue_state='actionable')::int as actionable_count,count(*) filter (where status='queued' and queue_state='deferred')::int as deferred_count from field_jobs where payload->>'stressRunId'=%s group by 1 order by 1""",(RUN_ID,)); field_breakdown=cur.fetchall()
    cur.execute("""select coalesce(payload->'contactResolution'->>'reasonCode','') as reason_code,count(*)::int as count from field_jobs where payload->>'stressRunId'=%s and status='queued' and queue_state='deferred' group by 1 order by count desc, reason_code asc""",(RUN_ID,)); deferred_reason_counts=cur.fetchall()
    cur.execute("""select coalesce(completed_payload->>'reasonCode','') as reason_code,count(*)::int as count from field_jobs where payload->>'stressRunId'=%s and status='failed' group by 1 order by count desc, reason_code asc""",(RUN_ID,)); failed_reason_counts=cur.fetchall()
    cur.execute("select greek_life_status,count(*)::int as count from school_greek_life_registry group by 1 order by 1"); school_policy_counts=cur.fetchall()
    cur.execute("select chapter_activity_status,count(*)::int as count from fraternity_school_activity_cache group by 1 order by 1"); activity_counts=cur.fetchall()
    cur.execute("select repair_state,count(*)::int as count from chapter_repair_jobs group by 1 order by 1"); repair_counts=cur.fetchall()
    cur.execute("""select runtime_mode,status,count(*)::int as count,avg(coalesce((summary->>'businessProgressCount')::int,0))::numeric(10,2) as avg_business_progress,avg(coalesce((summary->>'processed')::int,0))::numeric(10,2) as avg_processed,avg(coalesce((summary->>'requeued')::int,0))::numeric(10,2) as avg_requeued from field_job_graph_runs group by 1,2 order by 1,2"""); graph_runs=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,coalesce(fj.completed_payload->>'reasonCode','') as reason_code,fj.last_error,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='failed' order by fj.updated_at desc limit 15""",(RUN_ID,)); invalid_examples=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,coalesce(fj.payload->'contactResolution'->>'reasonCode','') as reason_code,fj.last_error,fj.payload->'provider_attempts' as provider_attempts,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='queued' and fj.queue_state='deferred' and coalesce(fj.payload->'contactResolution'->>'reasonCode','') in ('provider_degraded','transient_network') order by fj.updated_at desc limit 15""",(RUN_ID,)); provider_examples=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,coalesce(fj.payload->'contactResolution'->>'reasonCode','') as reason_code,ch.chapter_status,ch.website_url,ch.contact_email,ch.instagram_url,fj.last_error,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='queued' and fj.queue_state='deferred' and coalesce(fj.payload->'contactResolution'->>'reasonCode','') in ('dependency_wait','website_required') order by fj.updated_at desc limit 15""",(RUN_ID,)); dependency_examples=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,coalesce(fj.payload->'contactResolution'->>'reasonCode','') as reason_code,fj.payload->'chapterRepair'->>'state' as repair_state,fj.payload->'chapterRepair'->>'reasonCode' as repair_reason,fj.last_error,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='queued' and fj.queue_state='deferred' and coalesce(fj.payload->'contactResolution'->>'reasonCode','') in ('queued_for_entity_repair','identity_semantically_incomplete') order by fj.updated_at desc limit 15""",(RUN_ID,)); repair_examples=cur.fetchall()
with psycopg.connect(settings.database_url,row_factory=dict_row) as conn:
  with conn.cursor() as cur:
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,fj.completed_payload->>'status' as completed_status,fj.completed_payload->>'reasonCode' as reason_code,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='done' and fj.completed_payload->>'status'='inactive_by_school_validation' order by fj.updated_at desc limit 15""",(RUN_ID,)); inactive_examples=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,fj.completed_payload->>'reasonCode' as reason_code,fj.completed_payload->'decision_trace'->'search' as search_trace,fj.completed_payload->'decision_trace'->'trace' as trace,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='done' and fj.completed_payload->>'status'='terminal_no_signal' order by fj.updated_at desc limit 15""",(RUN_ID,)); terminal_examples=cur.fetchall()
    cur.execute("""select fr.slug as fraternity_slug,fj.payload->>'sourceSlug' as source_slug,ch.slug as chapter_slug,fj.field_name,fj.completed_payload->>'status' as completed_status,fj.completed_payload->>'sourceUrl' as source_url,fj.completed_payload->'decision_trace'->'search' as search_trace,fj.completed_payload->'decision_trace'->'trace' as trace,fj.completed_payload->'decision_trace'->'rejections' as rejections,fj.updated_at from field_jobs fj join chapters ch on ch.id=fj.chapter_id left join fraternities fr on fr.id=ch.fraternity_id where fj.payload->>'stressRunId'=%s and fj.status='done' and coalesce((fj.completed_payload->'decision_trace'->'search'->>'attempted')::int,0)>0 order by coalesce((fj.completed_payload->'decision_trace'->'search'->>'attempted')::int,0) desc, fj.updated_at desc limit 15""",(RUN_ID,)); real_search_examples=cur.fetchall()
lines=[]
lines.append('# Functionality Report: Stress Run Re-Audit\n')
lines.append('Date: `2026-04-09`\n')
lines.append(f'Run under analysis: `{RUN_ID}`\n')
lines.append('## Why This Version Replaces The Previous Report\n')
lines.append('The previous report was directionally useful, but one part of it was misleading: some rows displayed the shared provider-health probe bundle as if those were the chapter-specific queries for an individual field job. That was incorrect. The stress system uses a **global search preflight** to decide whether search providers are healthy enough to justify chapter-level fanout. Those probe queries are intentionally varied and are not the same thing as a chapter job search path.\n')
lines.append('This report corrects that by separating evidence into four classes:\n')
for b in ['`Global preflight probe evidence` - batch-level provider-health probes used to decide whether external search should run at all.','`Queue triage evidence` - invalid, dependency, or repair gating that prevented a job from entering wasteful work.','`Job-level decision trace` - the actual search queries and trace events for a specific chapter job when that job truly executed chapter-specific work.','`Outcome / impact` - what the system ultimately did with the job and how that affected downstream queue health.']: lines.append(f'- {b}')
lines.append('')
lines.append('## Scope And Evidence Base\n')
for b in ['`docs/reports/stress/stress-20260409-full.jsonl` for the 21 recorded stress batches and queue snapshots.','`docs/reports/stress/stress-20260409-post-hardstop.out` for the global provider-health preflight probe bundle and provider failure detail.','`docs/Diagrams/CURRENT_IMPLEMENTED_QUEUE_ARCHITECTURE.md` for the implemented lane-based architecture under test.','`CHANGELOG.md` for the patches landed during the run.','Live PostgreSQL queue state, graph-run summaries, repair tables, school-policy cache, and chapter-activity cache.','This chat context for the sequencing of fixes applied during the six-hour run.']: lines.append(f'- {b}')
lines.append('')
lines.append('## Executive Summary\n')
lines.append(f"The observed run window lasted **5:35:17** from `{first_ts}` to `{last_ts}`. The system entered the run with **{summary['job_count']:,}** stress-scope field jobs across **{summary['chapter_count']:,}** chapters and ended with **0 actionable** and **0 running** jobs. What remained at the end was not a hot failure tail: **{summary['queued_deferred']:,}** jobs were intentionally deferred behind provider health, repair, or dependency gates, and **{summary['failed_jobs']:,}** were blocked-invalid historical artifacts that triage removed from active execution.\n")
lines.append('The most important conclusion is that the architecture behaved correctly under stress once the queue policies were tightened. The dominant failure pressure over the six-hour window was **not** the graph runtime; it was the combination of (1) invalid historical junk already present in the queue, (2) degraded external search providers, and (3) prerequisite ordering bugs that initially let some low-value jobs stay actionable too long.\n')
lines.append('## KPI Table\n')
lines.append('| KPI | Value | Why it matters |')
lines.append('| --- | --- | --- |')
for k,v,w in [('Observed run window',f'{first_ts} to {last_ts}','Full six-hour stress window used for this report.'),('Recorded stress batches',len(batches),'21 discrete `batch_progress` events captured the queue state over time.'),('Runtime mode','langgraph_primary in all 21 batches','No fallback to legacy field-job runtime occurred during the stress window.'),('Policy pack','default in all 21 batches','There was no live policy-pack switching or online RL during the run.'),('Peak throughput',f'{peak_jpm:.2f} jobs/min','Highest drain rate after queue correctness patches landed.'),('Lowest throughput',f'{min_jpm:.2f} jobs/min','Slowest period when provider degradation dominated and almost everything requeued or deferred.'),('Average throughput',f'{avg_jpm:.2f} jobs/min','Mean batch-level throughput across the recorded run.'),('Batch-logged processed count',processed_total,'Useful because final `done` rows do not capture every intermediate action.'),('Batch-logged requeued count',requeued_total,'Shows how often work was preserved into a safer lane instead of hard-failed.'),('Final done jobs',f"{summary['done_jobs']:,}",'Jobs that completed with `updated`, `confirmed_absent`, `inactive_by_school_validation`, or `terminal_no_signal` outcomes.'),('Final failed jobs',f"{summary['failed_jobs']:,}",'Overwhelmingly blocked-invalid historical junk, not runtime crashes.'),('Final actionable queue',summary['queued_actionable'],'The hot queue drained cleanly to zero.'),('Final deferred queue',f"{summary['queued_deferred']:,}",'Deferred work remained behind explicit gates instead of silently thrashing.'),('Final running queue',summary['running_jobs'],'No stuck running jobs remained.'),('School policy cache',', '.join(f"{r['greek_life_status']}={r['count']}" for r in school_policy_counts),'Shows how much campus-policy validation had been persisted and reused.'),('Fraternity/school activity cache',', '.join(f"{r['chapter_activity_status']}={r['count']}" for r in activity_counts),'Shows how often chapter activity was definitively resolved.'),('Repair lane footprint',', '.join(f"{r['repair_state']}={r['count']}" for r in repair_counts),'Repair absorbed ambiguous identities rather than forcing them through contact enrichment.'),('Final deferred reasons','; '.join(f"{r['reason_code'] or '(blank)'}={r['count']}" for r in deferred_reason_counts[:7]),'Most deferred work was held behind repair, provider, identity, or website dependency gates.'),('Final failed reasons','; '.join(f"{r['reason_code'] or '(blank)'}={r['count']}" for r in failed_reason_counts[:5]),'Most failed rows were not real chapters.')]: lines.append(f'| {md(k)} | {md(v)} | {md(w)} |')
lines.append('')
lines.append('## Field-Level Breakdown\n')
lines.append('| Field | Done | Failed | Actionable | Deferred | Interpretation |')
lines.append('| --- | --- | --- | --- | --- | --- |')
interp={'find_website':'Website was the highest-yield lane and also the prerequisite lane that governed email quality.','find_email':'Email remained the most dependency-sensitive lane because it now waits for a confident website.','find_instagram':'Instagram sat between website and email: often recoverable, but still vulnerable to provider health and identity quality.'}
for r in field_breakdown: lines.append(f"| {md(r['field_name'])} | {r['done_count']} | {r['failed_count']} | {r['actionable_count']} | {r['deferred_count']} | {md(interp[r['field_name']])} |")
lines.append('')
lines.append('## Current Architecture Under Test\n')
lines.append('The run exercised the **implemented** backend-owned queue architecture, not the old distributed-control-plane design. The active lanes were the Request Worker, Contact Worker (`FieldJobSupervisorGraphRuntime + FieldJobGraphRuntime`), Repair Lane, and the persistence/worker tables exposed in the current architecture document. The most relevant architectural fact for this run is that queue ownership was singular and durable: the web layer was not owning these jobs, and the queue state was represented through typed relational fields and repair/defer lanes.\n')
for b in ['The contact lane could defer work safely without losing ownership or leaving phantom running jobs.','The repair lane could absorb semantically weak rows instead of forcing contact work to guess.','Queue triage could cancel invalid historical rows at scale because those rows were now first-class queue records with typed states.','The operator-visible run could be audited batch by batch through JSONL and DB snapshots.']: lines.append(f'- {b}')
lines.append('')
lines.append('## Subsystem Analysis\n')
lines.append('| Subsystem | What it did during the run | Evidence | Impact on reliability / performance |')
lines.append('| --- | --- | --- | --- |')
for row in [('Queue triage and typed queue state','Canceled invalid historical rows, deferred dependency/repair/provider work, and eventually drained actionable work to zero.','Final queue: actionable=0, running=0, failed invalid rows=6,307.','This subsystem did the most to stabilize throughput because it removed impossible work from the hot queue.'),('Search preflight and provider gating','Ran a shared provider-health probe bundle before chapter search fanout and short-circuited jobs when providers were unhealthy.','All 21 batches ran under unhealthy preflight conditions; provider-degraded deferred count=471.','This prevented wasted low-yield external search during provider collapse.'),('Field-job contact resolution graph','Executed actual chapter-specific search only when the admission gate and provider health allowed it.','; '.join(f"{r['runtime_mode']} {r['status']} count={r['count']} avgBusiness={r['avg_business_progress']} avgProcessed={r['avg_processed']} avgRequeued={r['avg_requeued']}" for r in graph_runs),'The runtime itself remained stable; the main bottleneck was search health and data quality, not graph execution.'),('Website prerequisite gating','Held email jobs until a confident website existed or a clear inactive/absent decision had been made.','Deferred reasons include dependency_wait=281 and website_required=96.','This improved precision and prevented email jobs from consuming slots without enough identity context.'),('Chapter repair lane','Absorbed semantically incomplete chapter identities and kept them out of blind contact search.','Repair queue states: queued=474, repair_exhausted=220, promoted_to_canonical_valid=14.','This shifted unresolved identity from search waste into an explicit repair workflow.'),('School policy and chapter activity validation','Confirmed active/inactive status using official school lists before some jobs escalated into broader search.','Activity cache: confirmed_inactive=37, confirmed_active=6.','This reduced low-yield search on chapters that should never have entered contact enrichment.'),('Observability and adaptation loop','Produced enough queue, provider, and outcome telemetry to support patch -> rerun -> verify loops during the same night.','21 JSONL batches + multiple `.out` rerun artifacts + CHANGELOG patch trail.','This is why the system could be improved during the run instead of only after the fact.')]: lines.append('| '+' | '.join(md(x) for x in row)+' |')
lines.append('')
lines.append('## Deeper Analysis And Research\n')
lines.append('### 1. The Shared Probe Bundle Was Real, But It Was Global\n')
lines.append('The recurring probe bundle from `stress-20260409-post-hardstop.out` consisted of these four global health queries:')
for q in PROBES: lines.append(f'- `{q}`')
lines.append('Those probes were not trying to find any specific chapter record. They were deliberately varied across fraternity names, universities, and field shapes to test whether the provider stack could successfully return *anything* representative. When the provider stack failed all four, the system marked preflight as degraded and **skipped chapter-specific fanout** for affected jobs. That is why rows such as `phi-gamma-delta-main / sigma-tau-chapter-university-of-washington / find_instagram` should have been read as “zero chapter-specific external queries were attempted because the provider layer was already unhealthy,” not “the system queried Sigma Chi for a Fiji chapter.”\n')
lines.append('### 2. The Largest Failure Class Was Not Search; It Was Bad Historical Inventory\n')
lines.append('The final failed-reason distribution makes this clear: `ranking_or_report_row=3427`, `year_or_percentage_as_identity=2570`, `school_division_or_department=170`, `history_or_timeline_row=137`, and `award_or_honor_row=3`. That means most of the jobs that “failed” in the final database were not legitimate fraternity chapter contact attempts. They were artifacts that should never have been in the contact lane. This matters because it changes the interpretation of the stress run: a large part of the night was spent teaching the queue to **refuse** work more accurately, not chasing real chapters poorly.\n')
lines.append('### 3. Throughput Increased Even While Providers Stayed Sick\n')
lines.append('Peak throughput (`104.40 jobs/min`) did not happen because providers recovered. It happened after queue correctness patches made the system more decisive about what **not** to search. In other words, high throughput later in the run mostly reflected faster triage, safer deferral, and clearer prerequisite enforcement, not a healthier external environment. That is why some late batches show strong jobs/minute while the dominant outcomes are still deferred repair, deferred provider degradation, and terminal no-signal.\n')
lines.append('### 4. There Was No Online Reinforcement Learning Loop During The Run\n')
lines.append('The stress path used `langgraph_primary` in all 21 recorded batches and `policy_pack=default` in all 21 recorded batches. There was no evidence of live policy-pack switching, online bandit exploration, or online reinforcement learning changing search behavior mid-run. The “learning” that happened during the six hours was deterministic and human-authored: telemetry exposed failure pressure, code was patched, and the same cohort was rerun. That distinction matters because the run’s improvements came from **architecture and queue policy changes**, not from a model autonomously adapting its own strategy.\n')
lines.append('### 5. What Still Consumes Risk After The Run\n')
lines.append('The final deferred queue shows the remaining risks clearly: '+', '.join(f"`{r['reason_code'] or '(blank)'}={r['count']}`" for r in deferred_reason_counts[:7])+'. The system is healthier because these are explicit, typed reasons rather than hidden thrash. But they still represent real follow-up work: a future run can only improve business yield further by either improving provider health, increasing authoritative school/chapter validation coverage, or draining the repair backlog.\n')
lines.append('## Change-Driven Adaptation During The Run\n')
lines.append('| Approx. phase | Observation from telemetry | Patch / decision made | Measured change |')
lines.append('| --- | --- | --- | --- |')
for row in [('Early run','Invalid historical rows dominated the hot queue immediately.','Blocked invalid entity types earlier and canceled sibling work for junk rows.','First recorded batch canceled 5,306 invalid jobs and re-shaped the queue.'),('Provider-collapse phase','Global preflight probes showed 0% success across the provider stack.','Added provider hard-stop / degraded-mode search skipping.','Later provider-degraded rows show 0 chapter-specific external queries instead of noisy fanout.'),('Dependency phase','Email jobs stayed actionable even when no confident website existed.','Deferred email behind website confidence prerequisites.','Actionable queue fell sharply in the 07:31 and 09:24 batches.'),('Oscillation phase','Deferred canonical jobs were being resurrected as actionable.','Preserved deferred canonical state during reconciliation.','Actionable queue spike at 08:20 was corrected in the next rerun.'),('Tail-drain phase','Repair promotion could still leave an email outlier actionable without a website.','Applied the same website prerequisite after repair promotion.','The final actionable queue dropped from 1 to 0.'),('Reporting correction','The previous report mislabeled probe queries as chapter-specific queries.','Re-audited evidence taxonomy and rebuilt the report.','This report now distinguishes global probes, queue triage, and job-level traces.')]: lines.append('| '+' | '.join(md(x) for x in row)+' |')
lines.append('')
lines.append('## Batch Timeline: 21 Recorded Queue Snapshots\n')
lines.append('| Timestamp | Processed | Requeued | Jobs/min | Actionable | Deferred | Invalid canceled | Dependency deferred | Repair queued | What changed operationally |')
lines.append('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
for b in batches:
    ts=b['timestamp']; br=b['batch_result']; delta=b['delta']; tri=br.get('queue_triage',{})
    note='; '.join(f"{o['outcome'] or '(blank)'}={o['count']}" for o in delta.get('outcomes',[])[:3])
    lines.append(f"| {md(ts)} | {br['processed']} | {br['requeued']} | {br['jobs_per_minute']:.2f} | {delta['counts']['actionable_jobs']} | {delta['counts']['deferred_jobs']} | {tri.get('invalidCancelled',0)} | {tri.get('dependencyDeferred',0)} | {tri.get('repairQueued',0)} | {md(note)} |")
lines.append('')
invalid_rows=[]
inv_effect={'ranking_or_report_row':'A report/ranking artifact would have stolen a worker slot from a real chapter; queue triage converted it into blocked-invalid.','year_or_percentage_as_identity':'A year/percentage token had been mistaken for a chapter identity; triage prevented blind search against nonsense.','school_division_or_department':'A school unit was treated as if it were a chapter; triage cut off contact work before any search began.','history_or_timeline_row':'A historical timeline row was present in the queue; triage removed it before it could recurse into contact search.','award_or_honor_row':'An award row would have created pure noise in the contact lane; triage blocked it immediately.'}
for r in invalid_examples: invalid_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],'queue triage only; 0 job search queries',r['reason_code'] or 'blank_reason',r['last_error'] or 'Canceled in queue triage before worker execution',inv_effect.get(r['reason_code'],'This row never should have been a contact job; triage removed it before search.')])
add_table(lines,'Failure Mode A: Invalid Historical Rows Entering The Contact Lane (15 examples)','These rows never executed chapter-specific search. They are evidence of historical data-quality debt and queue triage doing the right thing under load.',['Run','Source slug','Fraternity','Chapter slug','Field','Job-specific query path','Invalid classification','Recorded result','Cause -> effect'],invalid_rows)
shared='Shared degraded preflight bundle at 07:23:55 UTC: '+'; '.join(PROBES)
provider_rows=[]
for r in provider_examples: provider_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],'0 chapter-specific external queries; job deferred at preflight gate',shared,provsum(r['provider_attempts']),r['reason_code'],r['last_error'] or 'Deferred with provider health gate','Provider stack was already degraded -> chapter fanout was skipped -> queue cooled down safely instead of paying high query cost for low expected yield.'])
add_table(lines,'Failure Mode B: Provider-Degraded Deferrals (15 examples)','The key correction: the “probe queries” shown here are global batch probes, not chapter-specific searches for the listed chapter jobs.',['Run','Source slug','Fraternity','Chapter slug','Field','Chapter-specific query path','Global preflight probe evidence','Provider attempt pattern','Reason code','Recorded result','Cause -> effect'],provider_rows)
dep_rows=[]
for r in dependency_examples: dep_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],r['reason_code'],r['chapter_status'] or '','present' if r['website_url'] else 'missing','present' if r['contact_email'] else 'missing','present' if r['instagram_url'] else 'missing','No field-specific external search started; dependency gate fired first',r['last_error'] or 'Deferred behind website prerequisite','Email/related work stayed out of the hot queue until a confident website existed -> fewer low-identity searches and better precision.'])
add_table(lines,'Failure Mode C: Dependency And Website-Prerequisite Deferrals (15 examples)','These rows show jobs that were not allowed to start because prerequisite identity or website context was missing. This is a precision feature, not a runtime crash.',['Run','Source slug','Fraternity','Chapter slug','Field','Reason code','Chapter status','Website URL','Email','Instagram','Job-specific query path','Recorded result','Cause -> effect'],dep_rows)
repair_rows=[]
for r in repair_examples: repair_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],r['reason_code'],r['repair_state'] or '',r['repair_reason'] or '','No chapter-specific external search started; repair / semantic gate fired first',r['last_error'] or 'Deferred behind repair lane','Identity was not strong enough for contact enrichment -> work moved to repair instead of wasting search budget.'])
add_table(lines,'Failure Mode D: Repair-Lane And Semantic-Identity Deferrals (15 examples)','These examples show the repair lane doing architectural containment work. The contact system did not try to guess through weak identity.',['Run','Source slug','Fraternity','Chapter slug','Field','Contact reason code','Repair state','Repair reason','Job-specific query path','Recorded result','Cause -> effect'],repair_rows)
inactive_rows=[]
for r in inactive_examples: inactive_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],r['reason_code'],'School-validation search ran; chapter-level contact search did not continue after inactive confirmation',r['completed_status'],'Official school evidence or prior inactive state showed the chapter should not receive contact enrichment -> all sibling fields can terminate safely.'])
add_table(lines,'Failure Mode E: Inactive-By-School-Validation Outcomes (15 examples)','This is one of the most valuable generalized behaviors added during the recent work: stop contact resolution when official school evidence or cached inactivity says the chapter is not currently active.',['Run','Source slug','Fraternity','Chapter slug','Field','Inactive reason','Validation path','Recorded result','Cause -> effect'],inactive_rows)
term_rows=[]
for r in terminal_examples:
    s=r['search_trace'] or {}
    term_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],r['reason_code'],f"attempted={s.get('attempted',0)}; succeeded={s.get('succeeded',0)}; failed={s.get('failed',0)}; fanoutAborted={s.get('fanoutAborted',False)}",qpath(r['trace'],4),tevents(r['trace'],5),'Admission and cache signals indicated there was not enough identity or no new signal worth pursuing -> the job ended cleanly instead of requeueing forever.'])
add_table(lines,'Failure Mode F: Terminal No-Signal Outcomes (15 examples)','These rows are important because they are not “mystery failures.” They are explicit terminal outcomes where the system decided more searching was not justified.',['Run','Source slug','Fraternity','Chapter slug','Field','Reason code','Search summary','Query path','Trace events','Cause -> effect'],term_rows)
real_rows=[]
for r in real_search_examples:
    s=r['search_trace'] or {}
    real_rows.append([RUN_ID,r['source_slug'],r['fraternity_slug'],r['chapter_slug'],r['field_name'],r['completed_status'],r['source_url'] or '',f"attempted={s.get('attempted',0)}; succeeded={s.get('succeeded',0)}; failed={s.get('failed',0)}; fanoutAborted={s.get('fanoutAborted',False)}",qpath(r['trace'],8),tevents(r['trace'],8),json.dumps(r['rejections'] or [])[:220]])
add_table(lines,'True Chapter-Specific Search Traces Persisted During The Run (7 examples)','Only a small subset of jobs persisted real chapter-specific query traces. This section exists to show what those look like so they are not confused with global preflight probes.',['Run','Source slug','Fraternity','Chapter slug','Field','Outcome','Resolved source URL','Search summary','Actual chapter-specific query path','Trace events','Rejections'],real_rows)
lines.append('## What The Re-Audit Changes In Practical Terms\n')
for n in ['The row you called out for `phi-gamma-delta-main / sigma-tau-chapter-university-of-washington / find_instagram` did **not** mean the system searched Sigma Chi for Fiji. It meant the job executed **zero chapter-specific external queries** because the batch-level provider-health probe bundle had already collapsed. The old report used the wrong evidence label.','The most repeated table values in the old report happened because different evidence layers were being collapsed into a single `query path` column. In this report, the repeated parts are moved into section-level notes and only job-specific context stays in the row.','The system’s biggest problem during the stress window was not “it searched the wrong chapter over and over.” The larger issue was that too many invalid historical rows existed in the queue at all, and that provider degradation made even good search strategies expensive when not short-circuited.','The new architecture held up: backend-owned queue control, typed deferred states, repair containment, and school/activity validation all materially improved the system during the same run.']: lines.append(f'1. {n}' if not lines[-1].startswith('1.') else f'2. {n}')
lines.append('')
lines.append('## Residual Risks And Next Iteration Targets\n')
for b in ['Reduce the size of the `unknown` school-policy bucket so more chapters can be pruned or validated before contact work starts.','Drain the repair queue faster or improve promotion yield so fewer jobs sit at `identity_semantically_incomplete`.','Keep improving authoritative-source-first website discovery so more email jobs can progress out of `website_required`.','If provider health remains poor, consider stronger per-batch budgeting and source prioritization so the highest-yield chapters get the limited search budget first.','Continue report hygiene: keep global preflight evidence and job-level search traces separate in every future benchmark and stress report.']: lines.append(f'- {b}')
lines.append('')
REPORT.write_text('\n'.join(lines),encoding='utf-8')
print(f'Wrote {REPORT}')
if __name__=='__main__':
    pass

